name: Check tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          lfs: 'true'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
          cc: 1
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING=Debug \
                -DCMAKE_C_COMPILER:FILEPATH=clang \
                -DCMAKE_CXX_COMPILER:FILEPATH=clang++ \
                -S ${{github.workspace}} \
                -B ${{github.workspace}}/build
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config Debug --target all
      - name: Test
        run: |
          python ./x.py check --ignore-failed --output