name: Check tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  check-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING=Debug \
                -DCMAKE_C_COMPILER:FILEPATH=clang \
                -DCMAKE_CXX_COMPILER:FILEPATH=clang++ \
                -S ${{github.workspace}} \
                -B ${{github.workspace}}/build
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config Debug --target all
      - name: Test
        run: |
          python ./x.py check --ignore-failed --output