name: Deploy Sync
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING=Debug \
                -DCMAKE_C_COMPILER:FILEPATH=clang \
                -DCMAKE_CXX_COMPILER:FILEPATH=clang++ \
                -S ${{github.workspace}} \
                -B ${{github.workspace}}/build
      - name: Deploy
        run: |
          python ./x.py deploy
      - name: Sync
        run: |
          cd Deploy \
          git init \
          git config user.name "sync" \
          git config user.email "sync@nothing" \
          git remote add origin  ${{ secrets.REMOTE_URL }} \
          git add . \
          git commit -m "sync files from origin repo" \
          git push -u origin main --force
