name: Deploy & Sync
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING=Debug \
                -DCMAKE_C_COMPILER:FILEPATH=clang \
                -DCMAKE_CXX_COMPILER:FILEPATH=clang++ \
                -S ${{github.workspace}} \
                -B ${{github.workspace}}/build
      - name: Deploy
        run: |
          python -m pip install tomli
          python ./x.py deploy
      - name: Sync
        run: |
          REMOTE_URL=${{ secrets.REMOTE_URL }} sh sync.sh
